<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>cl.duoc.bancoxyz</groupId>
    <artifactId>bancoxyzbatch</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>BancoXYZ - Semana 8</name>
    <description>
        Proyecto agregador Maven de BancoXYZ para microservicios,
        configuración centralizada, descubrimiento de servicios,
        seguridad OAuth2 y tolerancia a fallos.
    </description>

    <modules>
        <!-- Infraestructura Spring Cloud -->
        <module>Semana 8/config-server</module>
        <module>Semana 8/discovery-server</module>

        <!-- Autenticación y API bancaria -->
        <module>Semana 8/auth-server</module>
        <module>Semana 8/bank-backend</module>

        <!-- Backend for Frontend -->
        <module>Semana 8/bff/bff-web</module>
        <module>Semana 8/bff/bff-mobile</module>
        <module>Semana 8/bff/bff-atm</module>
    </modules>

</project>