# ============================================
# BancoXYZ - BFF Web
# ============================================

spring.application.name=bff-web

# ============================================
# Spring Cloud Config
# ============================================

# Config Server centralizado de BancoXYZ.
# Sin "optional:" para exigir que el servidor
# de configuración esté disponible al iniciar.
spring.config.import=configserver:
spring.cloud.config.uri=http://127.0.0.1:8888

# ============================================
# Servidor
# ============================================

server.port=8081

# ============================================
# HTTPS
# ============================================

server.ssl.enabled=true
server.ssl.key-store=classpath:certs/bff-web.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-web

# ============================================
# Seguridad
# ============================================

security.tokens.web=${WEB_API_TOKEN:bancoxyz-web-demo-token-2026}
security.tokens.mobile=${MOBILE_API_TOKEN:bancoxyz-mobile-demo-token-2026}
security.tokens.atm=${ATM_API_TOKEN:bancoxyz-atm-demo-token-2026}

# ============================================
# OAuth2 Client - Authorization Code
# ============================================

spring.security.oauth2.client.registration.bancoxyz-client.provider=bancoxyz
spring.security.oauth2.client.registration.bancoxyz-client.client-id=bancoxyz-client
spring.security.oauth2.client.registration.bancoxyz-client.client-secret=bancoxyz-secret
spring.security.oauth2.client.registration.bancoxyz-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.bancoxyz-client.redirect-uri=https://127.0.0.1:8081/login/oauth2/code/bancoxyz-client
spring.security.oauth2.client.registration.bancoxyz-client.scope=openid,profile

spring.security.oauth2.client.provider.bancoxyz.authorization-uri=http://localhost:9000/oauth2/authorize
spring.security.oauth2.client.provider.bancoxyz.token-uri=http://auth-server:9000/oauth2/token
spring.security.oauth2.client.provider.bancoxyz.jwk-set-uri=http://auth-server:9000/oauth2/jwks
spring.security.oauth2.client.provider.bancoxyz.user-info-uri=http://auth-server:9000/userinfo
spring.security.oauth2.client.provider.bancoxyz.user-name-attribute=sub